# Generated by Django 4.0.5 on 2022-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUserСhoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.SlugField(unique=True)),
                ('user_id', models.IntegerField(default=1)),
                ('order_id', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products_users_choices',
            },
        ),
    ]
