# Generated by Django 4.0.5 on 2022-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('name', models.SlugField(max_length=150)),
                ('price', models.FloatField(db_index=True)),
                ('amount', models.IntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
