# Generated by Django 4.0.5 on 2022-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
