# Generated by Django 4.0.5 on 2022-07-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_article_alter_products_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
